FROM nginx:latest
# COPY ./html /usr/share/nginx/html
# RUN apt-get install --no-install-recommends -y apache2-utils
RUN apt-get update && apt-get install -y procps
RUN mkdir -p /etc/pwd
# RUN mkdir -p /home/secure
RUN mkdir /home/test 
RUN touch /home/test/m3.mp3
RUN touch /home/test/m4.mp3

